image: docker:18.09

variables:
  GIT_DEPTH: 0
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - check
  - build

lint:
  stage: check
  tags:
    - docker20
  image: node:18-alpine
  script:
    - cd ui && yarn install && yarn lint

build-ui:
  stage: build
  tags:
    - docker20
  image: node:18-alpine
  cache:
    paths:
      - ui/node_modules
  script:
    - cd ui && yarn install && yarn build
  artifacts:
    paths:
      - ui/dist
    expire_in: 1 day