version: "3.9"

services:

  traefik:
    image: traefik:v2.8
    container_name: traefik
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./ui/docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml
    - ./ui/docker/traefik/cert/:/certs/
    ports:
    - 443:443
    - 9091:9091
    healthcheck:
      test:
      - CMD
      - traefik
      - healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
    - vdp-form

  ui:
    image: node:14
    working_dir: /ui
    volumes:
    ## Main UI
    - ./ui/src:/ui/src
    - ./ui/.eslintrc.js:/ui/.eslintrc.js
    - ./ui/package.json:/ui/package.json
    - ./ui/tsconfig.json:/ui/tsconfig.json
    - ./ui/yarn.lock:/ui/yarn.lock
    ## Dev
    - ./ui/dev/cert:/ui/dev/cert
    - ./ui/dev/public:/ui/dev/public
    - ./ui/dev/src:/ui/dev/src
    - ./ui/dev/.eslintignore:/ui/dev/.eslintignore
    - ./ui/dev/.eslintrc.js:/ui/dev/.eslintrc.js
    - ./ui/dev/index.html:/ui/dev/index.html
    - ./ui/dev/package.json:/ui/dev/package.json
    - ./ui/dev/postcss.config.js:/ui/dev/postcss.config.js
    - ./ui/dev/quasar.config.js:/ui/dev/quasar.config.js
    - ./ui/dev/tsconfig.json:/ui/dev/tsconfig.json
    - ./ui/dev/yarn.lock:/ui/dev/yarn.lock
    command: sh -c 'yarn install && yarn dev --port=8081'
    networks:
    - vdp-form
    labels:
      service.name: vdp-form-ui
      traefik.enable: true
      traefik.http.routers.vdp-form-ui.rule: Host(`vdp-form-ui.localhost`)
      traefik.http.routers.vdp-form-ui.entrypoints: websecure
      traefik.http.routers.vdp-form-ui.tls: true
      traefik.http.services.vdp-form-ui.loadbalancer.server.port: 8081
    depends_on:
      traefik:
        condition: service_healthy

  backend:
    image: node:14
    working_dir: /backend
    volumes:
    - ./ui/dev-backend/cert:/backend/cert
    - ./ui/dev-backend/reports:/backend/reports
    - ./ui/dev-backend/src:/backend/src
    - ./ui/dev-backend/package.json:/backend/package.json
    - ./ui/dev-backend/tsconfig.json:/backend/tsconfig.json
    - ./ui/dev-backend/yarn.lock:/backend/yarn.lock
    command: sh -c 'yarn install && yarn build && yarn start --host --port=8082'
    networks:
    - vdp-form
    labels:
      service.name: vdp-form-backend
      traefik.enable: true
      traefik.http.routers.vdp-form-backend.rule: Host(`vdp-form-backend.localhost`)
      traefik.http.routers.vdp-form-backend.entrypoints: websecure
      traefik.http.routers.vdp-form-backend.tls: true
      traefik.http.services.vdp-form-backend.loadbalancer.server.port: 8082
    depends_on:
      traefik:
        condition: service_healthy

networks:
  vdp-form:
