version: "3.9"

services:

  traefik:
    image: traefik:v2.8
    container_name: traefik
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml
    - ./docker/traefik/cert/:/certs/
    ports:
    - 8081:8081
    - 443:443
    - 9091:9091
    healthcheck:
      test:
      - CMD
      - traefik
      - healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
    - vdp-form

  ui:
    image: node:14
    working_dir: /ui
    volumes:
    ## Main UI
    - ./src:/ui/src
    - ./.eslintrc.js:/ui/.eslintrc.js
    - ./package.json:/ui/package.json
    - ./tsconfig.json:/ui/tsconfig.json
    - ./yarn.lock:/ui/yarn.lock
    ## Dev
    - ./dev/cert:/ui/dev/cert
    - ./dev/public:/ui/dev/public
    - ./dev/src:/ui/dev/src
    - ./dev/.eslintignore:/ui/dev/.eslintignore
    - ./dev/.eslintrc.js:/ui/dev/.eslintrc.js
    - ./dev/index.html:/ui/dev/index.html
    - ./dev/package.json:/ui/dev/package.json
    - ./dev/postcss.config.js:/ui/dev/postcss.config.js
    - ./dev/quasar.config.js:/ui/dev/quasar.config.js
    - ./dev/tsconfig.json:/ui/dev/tsconfig.json
    - ./dev/yarn.lock:/ui/dev/yarn.lock
    command: sh -c 'yarn install && yarn dev --port=8081'
    networks:
    - vdp-form
    labels:
      service.name: vdp-form-ui
      traefik.enable: true
      traefik.http.routers.vdp-form-ui.rule: Host(`vdp-form-ui.localhost`)
      traefik.http.routers.vdp-form-ui.entrypoints: websecure
      traefik.http.routers.vdp-form-ui.tls: true
      traefik.http.services.vdp-form-ui.loadbalancer.server.port: 8081
    depends_on:
      traefik:
        condition: service_healthy

  backend:
    image: node:14
    working_dir: /backend
    volumes:
    - ./dev-backend/index.html:/backend/index.html
    - ./dev-backend/reports:/backend/reports
    - ./dev-backend/src:/backend/src
    - ./dev-backend/package.json:/backend/package.json
    - ./dev-backend/tsconfig.json:/backend/tsconfig.json
    - ./dev-backend/vite.config.ts:/backend/vite.config.ts
    - ./dev-backend/yarn.lock:/backend/yarn.lock
    command: sh -c 'yarn && yarn dev --host --port=8082'
    networks:
    - vdp-form
    labels:
      service.name: vdp-form-backend
      traefik.enable: true
      traefik.http.routers.vdp-form-backend.rule: Host(`vdp-form-backend.localhost`)
      traefik.http.routers.vdp-form-backend.entrypoints: websecure
      traefik.http.routers.vdp-form-backend.tls: true
      traefik.http.services.vdp-form-backend.loadbalancer.server.port: 8082
    depends_on:
      traefik:
        condition: service_healthy

  registry:
    image: verdaccio/verdaccio:5
    networks:
    - vdp-form
    labels:
      service.name: vdp-form-registry
      traefik.enable: true
      traefik.http.routers.vdp-form-registry.rule: Host(`vdp-form-registry.localhost`)
      traefik.http.routers.vdp-form-registry.entrypoints: web
      traefik.http.services.vdp-form-registry.loadbalancer.server.port: 4873
    depends_on:
      traefik:
        condition: service_healthy

networks:
  vdp-form:
